name: Manual Maven Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Build all modules for integration test
        run: mvn clean install

      - name: Ui testing
        run: |
          cd tobago-example/tobago-example-demo
          mvn verify -Pdocker -Pintegration-tests
